target_repo: ""
flavor: ansible_role
builds:
    - os: archlinux_latest
      archs:
        - linux/amd64
    - os: debian_bookworm
      archs:
        - linux/amd64
        - linux/arm64
    - os: debian_bookworm-slim
      archs:
        - linux/amd64
        - linux/arm64
    - os: rockylinux_9
      archs:
        - linux/amd64
        - linux/arm64
    - os: ubuntu_jammy
      archs:
        - linux/amd64
        - linux/arm64
    - os: ubuntu_plucky
      archs:
        - linux/amd64
        - linux/arm64
    - os: ubuntu_noble
      archs:
        - linux/amd64
        - linux/arm64
upstream:
    repo: ghcr.io/bradfordwagner/ansible
    tag: 6.2.0
