---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: pack
      register: test_output
    - name: assert binary prints help output
      debug:
        msg: '{{ test_output.stdout }}'
